services:
  backend:
    build: ./backend
    #platform: linux/amd64
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb+srv://sanikakadam604:eNNjyrDX4zQRSS2Y@cluster0.jhf3gzj.mongodb.net/Godowns
      - PORT=5000
    networks:
      - app-network

  frontend:
    build: ./frontend
    platform: linux/amd64
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app-network

  
volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
